image: Visual Studio 2019
  
before_build:
  - cmd: nuget restore

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

build:
  project: C:\projects\ankioverdrive\Anki.sln    # path to Visual Studio solution or project
  parallel: false                                       # enable MSBuild parallel builds
  verbosity: normal                                     # MSBuild verbosity level (quiet|minimal|normal|detailed)

after_build:
  - 7z a Anki.7z "%APPVEYOR_BUILD_FOLDER%\bin\Debug"

artifacts:  # Archive the generated packages in the ci.appveyor.com build report.  - path: bin\Debug\*
  - path: Anki.7z
    name: artifacts-all
